
#==============================================================================
#   Useful packages
#==============================================================================

# Packages frequently used 

# basic utilities

install.packages(c("acs",
                   "AER",
                   "boot", 
                   "car", 
                   "choroplethr",
                   "class", 
                   "colorspace",
                   "compareGroups",
                   "countrycode", 
                   "curl", 
                   "data.table",
                   "devtools",  
                   "doBy", 
                   "downloader", 
                   "dplyr", 
                   "erer",
                   "foreign", 
                   "gdata", 
                   "ggmap",
                   "ggplot2",
                   "git2r", 
                   "glmnet",  
                   "gmodels", 
                   "htmlwidgets",
                   "ivpack",
                   "ivmodel", 
                   "knitr", 
                   "lattice", 
                   "leaflet", 
                   "lfe", 
                   "lmtest", 
                   "magrittr", 
                   "maps", 
                   "mapproj", 
                   "maptools",
                   "markdown", 
                   "openintro", 
                   "OIdata", 
                   "plyr", 
                   "plm", 
                   "plotly", 
                   "quantreg", 
                   "RCurl", 
                   "rdrobust",
                   "readr", 
                   "readstata13", 
                   "readxl", 
                   "repmis",
                   "reshape", 
                   "reshape2", 
                   "rgdal",
                   "rmarkdown", 
                   "sampleSelection", 
                   "sandwich", 
                   "scholar", 
                   "shiny", 
                   "sp", 
                   "stargazer", 
                   "stringr", 
                   "survey", 
                   "survival",
                   "tidyr",
                   "tigris",
                   "USAboundaries", 
                   "WDI",
                   "xlsx",
                   "XML", 
                   "xtable",
                   "zoo")) 

# test